# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendapublica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.TextField(default='rua dos bobos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='cartaz',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='evento',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
