# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendapublica', '0002_auto_20161024_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='department',
        ),
        migrations.AlterField(
            model_name='evento',
            name='tags',
            field=models.ManyToManyField(blank=True, to='agendapublica.Tag'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(max_length=255),
        ),
    ]
